In [15]:
# Created by: Chen Da
# Created on: 2019.11.06

In [16]:
import pandas as pd
import numpy as np
import random

In [17]:
data_path = 'E:/cd/Automatic_Gate_Data/Rawdata/'

df_27 = pd.read_csv(data_path+'27_Lymphocytes.csv').iloc[:, 1:]
df_29 = pd.read_csv(data_path+'29_Monocytes.csv').iloc[:, 1:]

In [18]:
df_27.head()

,CD57,CD3,CD68,CD56,gdTCR,CCR6,CD14,IgD,CD123(IL-3R),CD85J,...,CD127(IL-7Ra),CD279(PD-1),CD38,Granzyme B,CD20,CD16,HLA-DR,CD4,CD8a,CD11b
0,0.000000,22.492535,0.187610,6.214056,0.000000,0.582940,0.0,0.000000,0.00000,1.053494,...,1.098302,0.000000,0.000000,2.481751,0.000000,0.000000,0.000000,0.286357,99.442238,16.957237
1,0.033216,34.419552,6.096721,0.000000,2.870183,0.000000,0.0,0.000000,0.00000,0.000000,...,84.917900,5.498103,7.818062,0.271232,3.062180,1.752819,0.000000,0.369598,150.735962,5.910296
2,0.000000,67.570862,0.224143,0.000000,0.000000,0.000000,0.0,0.397005,0.00000,0.000000,...,2.695918,0.000000,6.298023,0.000000,0.000000,0.000000,0.000000,73.634132,0.181764,0.000000
3,0.000000,26.342758,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.00000,0.675956,...,28.929289,0.000000,1.994209,0.672858,0.569359,2.234230,0.000000,30.956343,1.061158,0.000000
4,0.911928,0.000000,0.000000,0.000000,0.000000,11.272425,0.0,18.583693,1.99675,3.417376,...,1.432593,0.000000,0.000000,0.000000,93.856201,1.223260,98.217598,0.000000,0.000000,0.000000

In [19]:
df_27.columns, df_29.columns

(Index(['CD57', 'CD3', 'CD68', 'CD56', 'gdTCR', 'CCR6', 'CD14 ', 'IgD',
        'CD123(IL-3R)', 'CD85J', 'CD19', 'CD25', 'CD274(PD-L1)', 'CD278(ICOS)',
        'CD39', 'CD27', 'CD24', 'CD45RA', 'CD86', 'CD28', 'CD197(CCR7)',
        'CD11c ', 'CD33', 'CD152(CTLA-4)', 'FoxP3', 'CD161', 'CXCR5', 'CD66b',
        'CD183(CXCR3)', 'CD94', 'T-bet', 'Ki-67', 'CD127(IL-7Ra)',
        'CD279(PD-1)', 'CD38', 'Granzyme B', 'CD20', 'CD16', 'HLA-DR', 'CD4',
        'CD8a', 'CD11b'],
       dtype='object'),
 Index(['CD57', 'CD3', 'CD68', 'CD56', 'gdTCR', 'CCR6', 'CD14 ', 'IgD',
        'CD123(IL-3R)', 'CD85J', 'CD19', 'CD25', 'CD274(PD-L1)', 'CD278(ICOS)',
        'CD39', 'CD27', 'CD24', 'CD45RA', 'CD86', 'CD28', 'CD197(CCR7)',
        'CD11c ', 'CD33', 'CD152(CTLA-4)', 'FoxP3', 'CD161', 'CXCR5', 'CD66b',
        'CD183(CXCR3)', 'CD94', 'T-bet', 'Ki-67', 'CD127(IL-7Ra)',
        'CD279(PD-1)', 'CD38', 'Granzyme B', 'CD20', 'CD16', 'HLA-DR', 'CD4',
        'CD8a', 'CD11b'],
       dtype='object'))

In [20]:
df_27.shape, df_29.shape

((6532302, 42), (1078348, 42))

In [21]:
df_27['class'] = 0
df_29['class'] = 1

In [22]:
df_29.head()

,CD57,CD3,CD68,CD56,gdTCR,CCR6,CD14,IgD,CD123(IL-3R),CD85J,...,CD279(PD-1),CD38,Granzyme B,CD20,CD16,HLA-DR,CD4,CD8a,CD11b,class
0,0.000000,0.000000,5.846960,0.587310,0.000000,0.000000,29.527433,0.262298,0.0,32.568970,...,0.000000,73.474693,0.009541,3.464125,31.780527,265.568756,11.369659,0.000000,292.011475,1
1,0.000000,0.266199,0.533375,0.000000,0.000000,0.302912,14.597756,0.000000,0.0,42.792969,...,2.642175,16.254362,0.249321,0.000000,0.000000,644.618164,5.737424,0.000000,474.486908,1
2,0.000000,0.294077,7.074522,0.517519,0.000000,0.000000,0.000000,0.000000,0.0,65.373100,...,0.000000,8.678692,0.000000,0.000000,141.799820,246.559326,8.045889,0.000000,67.494438,1
3,0.000000,0.181499,13.968513,1.564623,0.000000,0.000000,8.065047,0.000000,0.0,0.869511,...,0.000000,6.699194,0.000000,0.000000,3.754273,13.559521,3.247906,4.689712,332.790527,1
4,1.406065,1.331363,0.000000,0.000000,2.553399,0.000000,9.688166,0.000000,0.0,4.410065,...,0.000000,40.607525,2.387861,0.000000,0.000000,23.337139,7.660386,1.389971,295.770782,1

In [23]:
def sample_func(df, num):
    df_index = list(df.index)
    select_index = random.sample(df_index, num)
    new_df = df.iloc[select_index, :]
    print(new_df.shape)
    return new_df

In [24]:
new_df_27 = sample_func(df_27, 500000)
new_df_29 = sample_func(df_29, 500000)

(500000, 43)
(500000, 43)

In [25]:
final_df = new_df_27.append(new_df_29)

In [26]:
final_df.shape

(1000000, 43)

In [27]:
final_df.tail()

,CD57,CD3,CD68,CD56,gdTCR,CCR6,CD14,IgD,CD123(IL-3R),CD85J,...,CD279(PD-1),CD38,Granzyme B,CD20,CD16,HLA-DR,CD4,CD8a,CD11b,class
971103,0.000000,0.000000,320.112457,3.607162,0.000000,0.792384,33.957085,0.000000,0.257810,11.484600,...,0.0,68.455536,3.399555,0.000000,28.132107,9.819628,2.597878,0.000000,354.286682,1
617328,0.000000,3.032812,225.915024,7.381096,1.016000,0.000000,33.160748,1.144017,3.149791,9.798360,...,0.0,8.465050,0.000000,0.000000,4.236640,13.712566,1.898083,0.064478,397.824371,1
8562,0.000000,1.870071,83.588074,3.417360,5.444834,0.000000,97.849396,2.384799,0.852940,18.583532,...,0.0,135.199188,1.194953,0.735995,13.150844,217.071915,8.371484,0.910202,306.440460,1
864385,0.611828,0.000000,170.738144,5.938947,0.000000,1.012237,32.983345,0.000000,0.000000,20.808529,...,0.0,17.016813,1.893043,0.000000,16.346296,19.335325,7.870751,1.834426,163.405762,1
686435,4.483353,0.000000,162.004211,4.297677,0.000000,0.000000,3.323896,0.000000,4.987186,70.824738,...,0.0,6.156518,1.168388,1.807102,105.630028,131.768295,2.502719,0.000000,8.299691,1

In [28]:
final_df.head()

,CD57,CD3,CD68,CD56,gdTCR,CCR6,CD14,IgD,CD123(IL-3R),CD85J,...,CD279(PD-1),CD38,Granzyme B,CD20,CD16,HLA-DR,CD4,CD8a,CD11b,class
2834132,13.843845,0.000000,55.135735,10.052266,6.926686,20.920048,8.012412,58.812294,0.000000,27.743259,...,0.758762,10.106405,0.000000,313.709839,22.644354,263.748322,0.000000,0.000000,0.153835,0
5545577,0.000000,0.000000,3.030959,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.630370,0.471020,9.146904,0.000000,0.000000,0.000000,4.450521,0
2019815,0.000000,0.000000,30.051870,3.899094,0.000000,14.816324,0.000000,73.959740,2.983433,7.239676,...,0.000000,8.513761,2.149584,23.342319,1.361476,155.066208,1.079741,0.000000,0.000000,0
6241532,54.121151,24.034622,43.104038,0.192697,0.000000,0.000000,0.512443,0.000000,0.000000,2.504778,...,0.521342,0.000000,47.181458,3.778270,0.775548,5.480249,2.166009,200.579025,1.175751,0
2837835,6.793794,35.400303,95.748894,13.343912,3.797017,0.689517,0.965004,1.165853,0.000000,0.000000,...,7.527720,20.759268,2.733933,0.000000,12.299205,1.087061,97.565582,1.967902,0.000000,0

In [29]:
final_df.index = [i for i in range(final_df.shape[0])]

In [30]:
final_df.head()

,CD57,CD3,CD68,CD56,gdTCR,CCR6,CD14,IgD,CD123(IL-3R),CD85J,...,CD279(PD-1),CD38,Granzyme B,CD20,CD16,HLA-DR,CD4,CD8a,CD11b,class
0,13.843845,0.000000,55.135735,10.052266,6.926686,20.920048,8.012412,58.812294,0.000000,27.743259,...,0.758762,10.106405,0.000000,313.709839,22.644354,263.748322,0.000000,0.000000,0.153835,0
1,0.000000,0.000000,3.030959,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.630370,0.471020,9.146904,0.000000,0.000000,0.000000,4.450521,0
2,0.000000,0.000000,30.051870,3.899094,0.000000,14.816324,0.000000,73.959740,2.983433,7.239676,...,0.000000,8.513761,2.149584,23.342319,1.361476,155.066208,1.079741,0.000000,0.000000,0
3,54.121151,24.034622,43.104038,0.192697,0.000000,0.000000,0.512443,0.000000,0.000000,2.504778,...,0.521342,0.000000,47.181458,3.778270,0.775548,5.480249,2.166009,200.579025,1.175751,0
4,6.793794,35.400303,95.748894,13.343912,3.797017,0.689517,0.965004,1.165853,0.000000,0.000000,...,7.527720,20.759268,2.733933,0.000000,12.299205,1.087061,97.565582,1.967902,0.000000,0

In [31]:
def split_func(data_frame, size=0.9):
    """
    Split the data into two data set
    :param data_frame: the name of input data
    :param size : the size of train data
    :return: train_data, test_data
    """
    data_frame = pd.DataFrame(data_frame.values,
                              index=[i for i in range(data_frame.values.shape[0])],
                              columns=data_frame.columns)

    healthy_data = data_frame[data_frame["class"] == 0]
    unhealthy_data = data_frame[data_frame["class"] == 1]

    healthy_index = list(healthy_data.index)
    unhealthy_index = list(unhealthy_data.index)

    healthy_train_data_index = random.sample(healthy_index, int(size * len(healthy_index)))
    unhealthy_train_data_index = random.sample(unhealthy_index, int(size * len(unhealthy_index)))

    healthy_test_data_index = list(set(healthy_index).difference(set(healthy_train_data_index)))
    unhealthy_test_data_index = list(set(unhealthy_index).difference(set(unhealthy_train_data_index)))

    train_index = list(set(healthy_train_data_index).union(set(unhealthy_train_data_index)))
    test_index = list(set(healthy_test_data_index).union(set(unhealthy_test_data_index)))

    train = data_frame.iloc[train_index, :]
    test = data_frame.iloc[test_index, :]

    return train, test

In [32]:
train, test = split_func(final_df)

In [33]:
train.to_csv(data_path+'traindata_27_29.csv', index=False)
test.to_csv(data_path+'testdata_27_29.csv', index=False)

In [34]:
final_df.to_csv(data_path+'rawdata_27_29.csv', index=False)